--fantomy
--trans 1
BEGIN TRANSACTION;
SELECT *
FROM b;
WAITFOR DELAY '00:00:10';
SELECT *
FROM b;
COMMIT TRANSACTION;

--trans 2

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET IMPLICIT_TRANSACTIONS off;
DBCC USEROPTIONS;


insert into b values(3);
